### ISSUE TITLE
ENH: add version check for GWT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [augustd/burp-suite-software-version-checks#1]
```
Please add a check for for GWT version, maybe in the form of a JS scan of a 
cache.html file with this:

$gwt_version = "2.5.1"

Thanks.
```

Original issue reported on code.google.com by `veggiespam` on 7 Jul 2015 at 5:27

**Comment by augustd** [comment]
Can you please send me some examples of files that include this identifier string? I will use them to test the regex.

**Comment by augustd** [comment]
Added a match rule for Google Web Toolkit.
