### ISSUE TITLE
CKEditor

### ISSUE THREAD

**Issue by unashamedgeek** [augustd/burp-suite-software-version-checks#12]
Proposed pattern for CKEditor

ckeditor.*([0-9]\.[0-9]\.[]0-9])

**Comment by augustd** [comment]
Can you please provide an example URL where you saw this pattern? I want to ensure that all patterns have a corresponding unit test.

**Comment by unashamedgeek** [comment]
I can't provide the exact URL since it was discovered during a pen test, but this is an example from the developer: https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js. In the first line of code past the comment, you'll see the version shown (version:"4.5.7"). I also tweaked it the regex a little CKEDITOR.*version:"([0-9].[0-9].[]0-9])
