### ISSUE TITLE
Patterns for mustache.js

### ISSUE THREAD

**Issue by nnposter** [augustd/burp-suite-software-version-checks#14]
Patterns for [mustache.js](https://github.com/janl/mustache.js):

Prevalent:
```
mustache\.version\s*=\s*'([\d.]+)'
```

Also seen:
```
name:"mustache.js",version:"([\d.]+)"
```
as seen at
http://ideas.quill.com/customer/jslibrary/1457334052000/ui-sfdc-javascript-impl/SfdcCore.js

**Comment by augustd** [comment]
Added these patterns. Thanks @nnposter !
