### ISSUE TITLE
Pattern for Prototype

### ISSUE THREAD

**Issue by nnposter** [augustd/burp-suite-software-version-checks#15]
A new pattern for [Prototype](http://prototypejs.org/):
```
Prototype\s*=\s*\{\s*Version:\s*["']([\d.]+)["']
```
as seen at:
https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js
http://ideas.quill.com/customer/resource/1431073472000/idea_js/all_min.js
http://ideas.quill.com/customer/resource/1431073472000/quill_allscripts_min_js

**Comment by augustd** [comment]
Added this pattern. Thanks @nnposter !
