### ISSUE TITLE
Contributors Wanted 

### ISSUE THREAD

**Issue by augustd** [augustd/burp-suite-software-version-checks#24]
@PeterMosmans @nnposter, 

Thanks for your contributions to this extension. My [Error Message Checks extension](https://github.com/augustd/burp-suite-error-message-checks) now also includes unit tests and Travis build. I'm looking for contributions of error messages encountered during testing and regexes to detect them. 

Thanks!

**Comment by PeterMosmans** [comment]
Thanks for the heads-up and the extension @augustd - Looks like another winner ;)
I'm going to install it and will provide you feedback/pull requests.

Cheers,

Peter
