### ISSUE TITLE
Tealeaf UI Capture

### ISSUE THREAD

**Issue by nnposter** [augustd/burp-suite-software-version-checks#5]
Proposed pattern for [IBM Tealeaf](http://www-03.ibm.com/software/products/en/customer-service-optimization):
```
"X-Tealeaf":"device\\s+\\(UIC\\)\\s+Lib/([\\d\\.]+)"
```
Seen at:
https://www.united.com/web/format/javascript/TeaLeaf/TeaLeaf.min.js
https://www.staples.com/sbdpas/20151106024917/js/tealeaf.js

**Comment by augustd** [comment]
Is Tealeaf actually setting those as headers?

**Comment by augustd** [comment]
Added two detection patterns for TeaLeaf: 

1. `X-Tealeaf\":\"device\s+\(UIC\)\s+Lib/([\d\.]+)` which detects the version number in Javascript files
2. `X-TeaLeaf-UIEventCapture-Version: ([0-9\\.]+)` which detects it in request headers.  

From reading the Javascript it seems like the intent of pattern 1 above is also to set headers, though I have not been able to locate an example of that header in practice. If you can find an example of that I will add it as well.

**Comment by nnposter** [comment]
Yup. The code is indeed setting up the header. If you hit http://www.staples.com/Shipping/cat_CL142725?fids=4225023386 you will see a subsequent XHR like the following:

```
POST http://www.staples.com/office/supplies/StaplesB2CPAS/TealeafTarget.jsp HTTP/1.1
Host: www.staples.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Content-Type: application/json; charset=UTF-8
X-Tealeaf: device (UIC) Lib/3.0.2.100
X-TealeafType: GUI
X-TeaLeaf-Page-Url: /Shipping/cat_CL142725
Referer: http://www.staples.com/Shipping/cat_CL142725?fids=4225023386
```

**Comment by augustd** [comment]
As it stands right now, the extension is only designed to scan _responses_, not _requests_. However, the patterns I added in faa8794f66b8ec6298e03d85b8fb8ed8e3c7c5ad should be able to detect the presence of the Tealeaf.js file, which will let you know that Tealeaf is in use by the application. Fair enough?
