### ISSUE TITLE
OpinionLab OnlineOpinion

### ISSUE THREAD

**Issue by nnposter** [augustd/burp-suite-software-version-checks#6]
Proposed pattern for [OpinionLab OnlineOpinion](http://www.opinionlab.com/):
```
\\bOnlineOpinion\\s+v([\\d\\.]+)\\b
```
Seen at:
https://assets.staples-static.com/sbdpas/onlineopinionV5/oo_tab.js
https://assets.staples-static.com/sbdpas/onlineopinionV5/oo_style_english.css

**Comment by augustd** [comment]
Thanks! Added a match rule for this software.
