### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by nnposter** [augustd/burp-suite-software-version-checks#7]
Proposed pattern for [AngularJS](https://angularjs.org/):
```
http://errors\\.angularjs\\.org/([\\d\\.]+)/
```
Seen at:
http://assets.staples-static.com/NDM2/pn/bui/20151117173906/js/ux2/asgard-dailydeals-min.js

**Comment by augustd** [comment]
Thanks! I've added this to the match rules file.
