### ISSUE TITLE
Custom Rules URL Not Saved

### ISSUE THREAD

**Issue by nopnopnoppopopret** [augustd/burp-suite-software-version-checks#8]
When I define my own custom URL with match-rules.tab and reload Burp, the plugin does not restore the custom URL.  Can you modify it to save those settings?  If I forget to add my custom URL, I lose all functionality for the plugin due to being in a closed network without access to github.

**Comment by augustd** [comment]
Thanks for the feedback. Will look into doing that.

**Comment by nopnopnoppopopret** [comment]
Thank you for the quick response.  I appreciate your plugin and use it on a daily basis.

**Comment by augustd** [comment]
I've just checked in changes to save the custom URL. I will submit it to Portswigger in the next few days -if you need it right away you can build from scratch.

**Comment by nopnopnoppopopret** [comment]
Thank you!  This will be very helpful!

**Comment by nopnopnoppopopret** [comment]
Were you able to submit this to PortSwigger for updates on the BApp store?

**Comment by augustd** [comment]
Submitted to PortSwigger today.
