### ISSUE TITLE
Scanner check doesn't obey URL Scope

### ISSUE THREAD

**Issue by jemjensen** [augustd/burp-suite-software-version-checks#92]
There doesn't seem to be a way to tell the tool to obey the current scope, which sometimes results in hundreds or thousands of false positives for domains outside of the scope of a test. Since it is a passive scan it isn't as crucial as if it was an active scan but it can still be quite annoying and result in larger-than-necessary state files.

**Comment by augustd** [comment]
I checked in a change that will fix this. 

Note that you can also use the Tools Scope component to narrow down which tools will be monitored (for example by switching off proxy)

I usually use FoxyProxy to only send URLs I'm testing in to Burp. This speeds up other browsing and helps keep state files small. Alternatively you can now use Burp's built in Chromium browser for testing and do you normal browsing on a completely different browser.
